import Head from "next/head";
import styled from "styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>What a Chad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/trident.png" />
      </Head>
      <MainContainer>
        contents
      </MainContainer>
    </>
  );
}

const MainContainer = styled.div`
  padding: 40px 20px;
  display: flex;
  width: 100%;
`;
