import Head from "next/head";
import React from "react";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const Workout = () => {
  return (
    <div>
      <Head>
        <title>Workout | What a Chad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/trident.png" />
      </Head>
      <Header />
      <main>WaC Workout page</main>
      <Footer />
    </div>
  );
};

export default Workout;
