import Head from "next/head";
import React from "react";

const Workout = () => {
  return (
    <>
      <Head>
        <title>Workout | What a Chad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/trident.png" />
      </Head>
      <main>WaC Workout page</main>
    </>
  );
};

export default Workout;
